name: FCS-actions-image-scan-test
on: [push, pull_request]

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Create secret files
        run: |
          echo "${{ secrets.FALCON_CLIENT_ID }}" > /tmp/client_id
          echo "${{ secrets.FALCON_CLIENT_SECRET }}" > /tmp/client_secret
          echo "${{ secrets.FALCON_API_URL }}" > /tmp/api_url
        
      - name: Build Docker image with secrets
        run: |
          docker build \
            --secret id=client_id,src=/tmp/client_id \
            --secret id=client_secret,src=/tmp/client_secret \
            --secret id=api_url,src=/tmp/api_url \
            --platform linux/amd64 \
            -t fcs-scanner .
            
      - name: Clean up secret files
        if: always()
        run: |
          rm -f /tmp/client_id /tmp/client_secret /tmp/api_url

      - name: Scan Container Image using FCS-action
        uses: crowdstrike/fcs-action@v2.0.1
        with:
          falcon_client_id: ${{ secrets.FALCON_CLIENT_ID }}
          falcon_region: 'us-1'
          scan_type: image
          image: fcs-scanner:latest
          output_path: image-scan-results/image_scan_results.json
          report_formats: sarif
        env:
          FALCON_CLIENT_SECRET: ${{ secrets.FALCON_CLIENT_SECRET }}
      

      - name: Upload image sarif file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ./image-scan-results/
        
